config/routes.rb
Rails.application.routes.draw do
root 'access#login'

  get '/login', to: "access#login", as: 'login'

  get '/signup', to: "access#signup", as: 'signup'

  post '/login', to: "access#attempt_login"

  post '/signup', to: "access#create"

  get '/home', to: "access#home", as: 'home'

  delete '/logout', to: "access#logout", as: "logout"
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password 
	validates :username, uniqueness: true, presence: true
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
	before_action :prevent_login_signup, only: [:signup, :login]

  def signup
  	@user = User.new
  end

  def create
  	@user = User.create user_params
  	if @user.save
  		session[:user_id] = @user.id
  		redirect_to home_path, notice: "Successfully created"
  	else
  		render :signup
  	end
  end

  def attempt_login
  	if params[:username].present? && params[:password].present?
      found_user = User.where(username: params[:username]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
        	if authorized_user
						render :home, notice: "You've succesfully logged in!"
						else
						redirect_to login_path, notice: "Your password is invalid"
      		end
      	else
      		redirect_to login_path, notice: "Your username is invalid"
   		end
  	end
  end

  def home
  end

  def logout
  	session[:user_id] = nil
  	render :logout
  end

  def login

  end

  private
  def user_params
  	params.require(:user).permit(:username, :password, :password_digest)
  end

  def prevent_login_signup
  	if session[:user_id]
  		redirect_to home_path
  	end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/access/home.html.erb
<h1>Welcome Home!</h1>

<h3>You made it :)</h3>


<%= link_to "Log Out", logout_path, method: :delete %>

app/views/access/login.html.erb
<br><br>

<%= form_tag(login_path) do %>

  <%= label_tag(:username)%>
  <%= text_field_tag(:username, params[:username], autofocus: true)%>


  <%= label_tag(:password)%>
  <%= password_field_tag(:password)%>

  <%= submit_tag("Log in", class: "btn btn-primary") %>

<% end %>
<br><br><br>
<%= link_to "Don't have an account? Sign up here", signup_path%>

app/views/access/logout.html.erb
<h1>Thanks for stopping by! :)</h1>


<%= link_to "Log In", login_path  %>

app/views/access/signup.html.erb
<h1>Signup</h1>

<%= simple_form_for(@user, url: signup_path) do |f|%>
  <p>
    <%= f.input(:username, autofocus: true) %>
  </p>
  <p>
    <%= f.input(:password, required: true) %>
  </p>
  <p>
    <%= f.button(:submit, "Signup", class: "btn btn-primary") %>
  </p>
    <%= link_to "Have an account already? Log in here", login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todosession</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body class = "container text-center">

<% flash.each do |key, value| %>
  <% if key == "notice" %>
    <%= content_tag :div, value, class: "text-center alert alert-warning" %>
  <% elsif key == "alert" %>
    <%= content_tag :div, value, class: "text-center alert alert-danger" %>
  <% else %>
    <%= content_tag :div, value, class: "text-center alert alert-success" %>
  <% end %>
<% end %>

<%= yield %>

</body>
</html>